stages:
    - build
    - deploy

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - npm install -DskipTests=true
        - npm run build
    tags:
        - dev-server

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - sudo cp -r ./dist /data/trello-web/
        - echo VITE_API_ROOT = ${VITE_API_ROOT} >> .env
        - sudo mv .env /data/trello-web/
        - sudo chown -R trello-web:trello-web /data/trello-web/
        - sudo chmod -R 750 /data/trello-web/
        # - npm install -DskipTests=true
        # - npm run build
        # - sudo cp -r ./dist /data/trello-web/
        # - sudo chown -R trello-web:trello-web /data/trello-web/
        # - sudo chmod -R 750 /data/trello-web/
    tags:
        - dev-server

