stages:
    - deploy

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: clone
    script:
        - yarn -DskipTests=true
        - yarn build
        - sudo cp -r ./dist /data/trello-web/
        # - sudo chown -R trello-web:trello-web /data/trello-web/dist/
        # - sudo chmod -R 750 /data/trello-web/dist/
    tags:
        - server

