stages:
    - build
    - deploy
    - log

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - yarn -DskipTests=true
        - yarn build
        - sudo rm -rf /data/trello-web/
        - sudo mv dist /data/trello-web/dist
    tags:
        - server

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    when: manual
    script:
        - sudo chown -R trello-web:trello-web /data/trello-web/
        - sudo chmod -R 750 /data/trello-web/
        - sudo usermod -aG trello-web www-data
    tags:
        - server
