stages:
    - build
    - deploy
    - log

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - yarn -DskipTests=true
        - yarn build
        - sudo rm -rf /data/trello-web/
        - sudo mv -r ./dist/ /data/trello-web/
    tags:
        - server
