stages:
    - deploy

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: clone
    script:
        - yarn -DskipTests=true
        - yarn build
        - sudo mv ./dist /data/trello-web/dist/
    tags:
        - server

